generate launch.json for vscode debug
AdinAck/cargo-embassy pull request #18
Opened 2024-08-04 11:28 UTC by listentodella

Users can use probe-rs debug through vscode.
This patch can generate a proper launch.json based on chipname.

2024-08-04 12:14 UTC, listentodella commented
![image](https://github.com/user-attachments/assets/985698cc-347f-4276-9cfc-f0576ebeb7d1)

2024-08-04 16:07 UTC, AdinAck requested changes
Thanks! This looks cool, I left some comments.

2024-08-04 16:07 UTC, AdinAck commented on src/templates/launch.json.template
> +          "programBinary": "target/thumbv7m-none-eabi/debug/demo",
Perhaps this should say "bin_dir" or even just ""?

2024-08-04 16:07 UTC, AdinAck commented on src/init.rs
> +        self.init_debug_config(&chip, &probe_target_name, &args.name)?;
I'm not a fan of generating this file unconditionally. Many people (myself included) *do not* use VSCode and won't want our workspace cluttered with a `.vscode` folder.

An additional flag like `--vscode-launch` would be good, I think.

2024-08-05 12:53 UTC, listentodella commented
Thanks for your advice! I resolved above comments.

2024-08-05 15:22 UTC, AdinAck approved these changes
LGTM! Thanks!

2024-08-05 15:27 UTC, merged

2024-08-05 15:28 UTC, AdinAck commented
I can't think of a way to test this functionality in CI, so I guess it can remain unchanged.